### ISSUE TITLE
Implement ElectronJS

### ISSUE THREAD

**Issue by AnthoDingo** [oskardrevetnitschke/node_keyboard#5]
Possibilité d'évolution : https://www.electronjs.org/

Actuellement, il faut compiler le package 'sendinput'.
En passant le code sur Electron, il sera possible de faire une application Windows et de la mettre dans le systray de Windows.

En utilisant Electron, il sera également possible de voir pour la compilation automatique sur Github et ainsi proposé une version utilisable directement sans compilation.

Electron propose également un système de mise à jours automatique basé sur le repo Github.

**Comment by sikelio** [comment]
C'est prévu que je passe par électron :)
