### ISSUE TITLE
Crash when no port is defined

### ISSUE THREAD

**Issue by AnthoDingo** [oskardrevetnitschke/node_keyboard#6]
Could you specify default value if none is define ?

```javascript
const PORT = process.env.APP_PORT;
```

PORT is undefined

**Comment by sikelio** [comment]
The issues should be normally solved. I updated the main branch with a patch.
By default the port will be 3000 if undefined in the .env file. It's the same for the salt key.
But for the token, the app will stop and write in the console that the token should be declared in the .env file
